# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - playground-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Debug - Check file structure (Windows)
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of root:"
          dir
          echo "Looking for .csproj files:"
          Get-ChildItem -Recurse -Filter "*.csproj" | Select-Object FullName
          echo "Looking for .sln files:"
          Get-ChildItem -Recurse -Filter "*.sln" | Select-Object FullName

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release ./azure-playground/azure-playground.csproj

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A4803B696CB437197DC5C28C8702BC4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D9C65B22F430477FA221F3BBA44F2514 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E636BA06D1EB4490B68DAD67681980A6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'playground-app'
          slot-name: 'Production'
          package: .
          
